### ISSUE TITLE
The front page readme should be updated with additional details

### ISSUE THREAD

**Issue by samsmithnz** [isaacrlevin/WorkFlowGenerator#11]
### Discussed in https://github.com/isaacrlevin/WorkFlowGenerator/discussions/8

<div type='discussions-op-text'>

<sup>Originally posted by **samsmithnz** November 24, 2021</sup>
Include:

- a simple explanation of what the repo/app does, why it exists, and how it works. 
- a simple example of how to use the app e.g. `workflowgeneration -repo:isaacrlevin/workflowgenerator -type:test -dotnetversion:6.x`
- link to contribution rules (start a discussion before big features, it's ok to branch/pr small things)
- perhaps a simple roadmap/call to action/ where you need help </div>

**Comment by isaacrlevin** [comment]
Fixed
